---
title: "Chapter24"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


#Item based Collaborative Filtering
```{r}
library(lsa)
setwd("~/Desktop/Acads/Excel Files/Chapter 24 Excel Files")
ratings <- read.xlsx("finalitembasednew.xlsx",4)

ratings[is.na(df)] <- 0
ratings
x <- df[,2:7]
item_sim = cosine(as.matrix(x))

 rec_itm_for_user = function(userno)
 {
   #extract all the movies not rated 
   userRatings = ratings[userno,]
   non_rated_movies = list()
   rated_movies = list()
   for(i in 2:ncol(userRatings)){
     if(is.na(userRatings[,i]))
     {
       non_rated_movies = c(non_rated_movies,colnames(userRatings)[i])
     }
     else
     {
       rated_movies = c(rated_movies,colnames(userRatings)[i])
     }
   }
   non_rated_movies = unlist(non_rated_movies)
   rated_movies = unlist(rated_movies)
   #create weighted similarity for all the rated movies
   non_rated_pred_score = list()
   for(j in 1:length(non_rated_movies)){
     temp_sum = 0
     df = item_sim[which(rownames(item_sim)==non_rated_movies[j]),]
     for(i in 1:length(rated_movies)){
       temp_sum = temp_sum+ df[which(names(df)==rated_movies[i])]
        }
     weight_mat = df*ratings[userno,2:7]
     non_rated_pred_score = c(non_rated_pred_score,rowSums(weight_mat,na.rm=T)/temp_sum)
     }
   pred_rat_mat = as.data.frame(non_rated_pred_score)
   names(pred_rat_mat) = non_rated_movies
   for(k in 1:ncol(pred_rat_mat)){
     ratings[userno,][which(names(ratings[userno,]) == names(pred_rat_mat)[k])] = pred_rat_mat[1,k]
   }
   return(ratings[userno,])
 }
rec_itm_for_user(4)
```

#User based Collaborative filtering

```{r}
library(lsa)
setwd("~/Desktop/Acads/Excel Files/Chapter 24 Excel Files")
critics <- read.xlsx("finalitembasednew.xlsx",4)
critics
library(lsa)

#calculate the euclidian distance 
#EUD = dist(critics[,2:7])
#cosine similarity calculation
x  = critics[,2:7]
x[is.na(x)] = 0
user_sim = cosine(as.matrix(t(x))) #user similarity
#Recommending items
#for Toby

#create weightge matrix
weight_mat = user_sim[,6]*critics[,2:6]

rec_itm_for_user = function(userNo)
{
#calcualte column wise sum
col_sums= list()
rat_user = critics[userNo,2:ncol(critics)]
x=1
tot = list()
z=1

for(i in 1:ncol(rat_user)){
  if(is.na(rat_user[1,i]))
  {
    
    col_sums[x] = sum(weight_mat[,i],na.rm=TRUE)
    x=x+1
    
    temp = as.data.frame(weight_mat[,i])
    
    sum_temp=0
    
    for(j in 1:nrow(temp)){
      if(!is.na(temp[j,1])){
        sum_temp = sum_temp+user_sim[j,ncol(rat_user)]
      }
      
    }
    tot[z] = sum_temp
    z=z+1
  } 
  
  
}
z=NULL

z=1
for(i in 1:ncol(rat_user)){
  if(is.na(rat_user[1,i]))
  {
    rat_user[1,i] = col_sums[[z]]/tot[[z]]
    z=z+1
  }
  
}

return(rat_user)
}


#to get N recommendations:
rec_itm_for_user(4) 
```